---
title: "Visualizations"
---

## Age Definitions by Gender

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

verbum_df <- readxl::read_xlsx("VERBUM.xlsx")

verbum_clean <- verbum_df |> 
  rename_with(~ tolower(str_replace_all(.x, " +", "_"))) |> 
  mutate(across(where(is.character), ~ na_if(.x, "n/a"))) |> 
  separate(primary_references, into = c("author", "title", "para")) |> 
  group_by(author, title, para) |> 
  mutate(local_id = row_number(), .after = para)
```


```{r echo=FALSE, message=FALSE}
verbum_clean |> 
  count(gender, age_relative_definition) |> 
  mutate(age_relative_definition = str_remove(age_relative_definition, " age")) |> 
  filter(!is.na(age_relative_definition)) |> 
  ggplot(aes(age_relative_definition, n, fill = gender)) +
  geom_col(position = "stack") +
  labs(x = NULL, y = "Count", 
       title = "Age Definitions by Gender") +
  theme_minimal() +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

## Age Labels by Terms

```{r}
#| echo: false
#| warning: false


verbum_clean |> 
  count(term, age_relative_definition) |> 
  filter(!is.na(age_relative_definition)) |> 
  mutate(term = str_replace(term, "[/ⲻ]", " ")) |> 
  ggplot(aes(term, n, fill = age_relative_definition)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~age_relative_definition, scales = "free") +
  coord_flip() +
  theme_minimal() +
  labs(title = "Funky Coptic Stuff") +
  theme(axis.text.y = element_text(family = "Noto Sans Coptic", size = 10),
        strip.text = element_text(face = "bold", size = 11))
```